// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dashboard/stats": {
            "get": {
                "description": "Get aggregated stats including total dependencies, license distribution, ecosystem distribution, compliance status, and vulnerability severity counts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get dashboard statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Organisation ID to filter by",
                        "name": "organisation_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Product ID to filter by",
                        "name": "product_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Repository ID to filter by",
                        "name": "repository_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.DashboardStats"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/licenses": {
            "get": {
                "description": "Get a list of all unique licenses found in the latest SBOMs, with counts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compliance"
                ],
                "summary": "List all licenses",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Organisation ID to filter by",
                        "name": "organisation_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.LicenseCountResponse"
                            }
                        }
                    }
                }
            }
        },
        "/licenses/{name}": {
            "get": {
                "description": "Get a list of components across all repositories that use a specific license.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compliance"
                ],
                "summary": "Get license details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "License Name (use 'Unknown' for empty licenses)",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Organisation ID to filter by",
                        "name": "organisation_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.LicenseUsageResponse"
                            }
                        }
                    }
                }
            }
        },
        "/organisations": {
            "get": {
                "description": "Get a list of all organisations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organisations"
                ],
                "summary": "List organisations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Organisation"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new organisation with the given name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organisations"
                ],
                "summary": "Create a new organisation",
                "parameters": [
                    {
                        "description": "Organisation object",
                        "name": "organisation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateOrganisationInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Organisation"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/organisations/{id}": {
            "put": {
                "description": "Update the name of an existing organisation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organisations"
                ],
                "summary": "Update an organisation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Organisation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Organisation object",
                        "name": "organisation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateOrganisationInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Organisation"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an organisation by ID",
                "tags": [
                    "organisations"
                ],
                "summary": "Delete an organisation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Organisation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/policies": {
            "get": {
                "description": "Get a list of policies, optionally filtered by organisation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "policies"
                ],
                "summary": "List policies",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Organisation ID to filter by",
                        "name": "organisation_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Policy"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new compliance policy for an organisation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "policies"
                ],
                "summary": "Create a new policy",
                "parameters": [
                    {
                        "description": "Policy object",
                        "name": "policy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreatePolicyInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Policy"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/policies/{id}": {
            "get": {
                "description": "Get detailed information about a policy, including products using it, compliance percentage, and a list of components breaching the policy.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "policies"
                ],
                "summary": "Get policy details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Policy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.PolicyDetailsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "description": "Get a list of products, optionally filtered by organisation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "List products",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Organisation ID to filter by",
                        "name": "organisation_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Product"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new product under an organisation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Create a new product",
                "parameters": [
                    {
                        "description": "Product object",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateProductInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Product"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/products/{id}/policy": {
            "put": {
                "description": "Assign or update a compliance policy for a specific product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Update product policy",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Policy ID wrapper",
                        "name": "policy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateProductPolicyInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories": {
            "get": {
                "description": "Get a list of repositories, optionally filtered by product or organisation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List repositories",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID to filter by",
                        "name": "product_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Organisation ID to filter by",
                        "name": "organisation_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Repository"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new repository under a product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Create a new repository",
                "parameters": [
                    {
                        "description": "Repository object",
                        "name": "repository",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateRepositoryInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Repository"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}": {
            "get": {
                "description": "Get a repository by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Get a repository",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Repository"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/sbom": {
            "get": {
                "description": "Get the most recent SBOM (with components and vulnerabilities) for a repository",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Get repository SBOM",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SBOM"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/scan": {
            "post": {
                "description": "Trigger a new SBOM scan for the given repository",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Trigger a repository scan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "222": {
                        "description": "",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/scans": {
            "get": {
                "description": "Get a history of SBOM scans for a repository",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List repository scans",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SBOM"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sboms/upload": {
            "post": {
                "description": "Upload an SBOM file (CycloneDX, SPDX, or Syft) and parse its contents. Optionally associate it with a repository.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sboms"
                ],
                "summary": "Upload an SBOM",
                "parameters": [
                    {
                        "type": "file",
                        "description": "SBOM file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Repository ID to associate the SBOM with",
                        "name": "repository_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.SBOM"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sboms/{id}": {
            "get": {
                "description": "Get an SBOM by ID, including its components and vulnerabilities",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sboms"
                ],
                "summary": "Get an SBOM",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "SBOM ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SBOM"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CreateOrganisationInput": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "handlers.CreatePolicyInput": {
            "type": "object",
            "required": [
                "name",
                "organisation_id"
            ],
            "properties": {
                "allowed_licenses": {
                    "type": "string"
                },
                "disallowed_deps": {
                    "type": "string"
                },
                "disallowed_licenses": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organisation_id": {
                    "type": "integer"
                }
            }
        },
        "handlers.CreateProductInput": {
            "type": "object",
            "required": [
                "name",
                "organisation_id"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "organisation_id": {
                    "type": "integer"
                }
            }
        },
        "handlers.CreateRepositoryInput": {
            "type": "object",
            "required": [
                "name",
                "product_id",
                "repo_url"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "repo_url": {
                    "type": "string"
                }
            }
        },
        "handlers.DashboardStats": {
            "type": "object",
            "properties": {
                "compliance": {
                    "description": "allowed, denied, unknown",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.DataPoint"
                    }
                },
                "ecosystems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.DataPoint"
                    }
                },
                "licenses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.DataPoint"
                    }
                },
                "total_dependencies": {
                    "type": "integer"
                },
                "vulnerabilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.DataPoint"
                    }
                }
            }
        },
        "handlers.DataPoint": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "handlers.LicenseCountResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "handlers.LicenseUsageResponse": {
            "type": "object",
            "properties": {
                "component_name": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "repository_name": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "handlers.PolicyBreach": {
            "type": "object",
            "properties": {
                "component_name": {
                    "type": "string"
                },
                "license": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "repository_name": {
                    "type": "string"
                }
            }
        },
        "handlers.PolicyDetailsResponse": {
            "type": "object",
            "properties": {
                "breaches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.PolicyBreach"
                    }
                },
                "compliance_percent": {
                    "type": "number"
                },
                "denied_components": {
                    "type": "integer"
                },
                "policy": {},
                "products": {},
                "total_components": {
                    "type": "integer"
                }
            }
        },
        "handlers.UpdateProductPolicyInput": {
            "type": "object",
            "properties": {
                "policy_id": {
                    "type": "integer"
                }
            }
        },
        "models.Component": {
            "type": "object",
            "properties": {
                "compliance_reason": {
                    "type": "string"
                },
                "compliance_status": {
                    "description": "allowed, denied, unknown",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "license": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "purl": {
                    "type": "string"
                },
                "sbom_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                },
                "vulnerabilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Vulnerability"
                    }
                }
            }
        },
        "models.Organisation": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "policies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Policy"
                    }
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Product"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Policy": {
            "type": "object",
            "properties": {
                "allowed_licenses": {
                    "description": "Comma-separated",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "disallowed_deps": {
                    "description": "Comma-separated (partial name match)",
                    "type": "string"
                },
                "disallowed_licenses": {
                    "description": "Comma-separated",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "organisation_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Product": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "organisation_id": {
                    "type": "integer"
                },
                "policy": {
                    "$ref": "#/definitions/models.Policy"
                },
                "policy_id": {
                    "type": "integer"
                },
                "repositories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Repository"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Repository": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_scan": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "product": {
                    "$ref": "#/definitions/models.Product"
                },
                "product_id": {
                    "type": "integer"
                },
                "repo_url": {
                    "type": "string"
                },
                "sboms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SBOM"
                    }
                },
                "status": {
                    "description": "pending, scanning, completed, failed",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.SBOM": {
            "type": "object",
            "properties": {
                "components": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Component"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "format": {
                    "description": "CycloneDX, SPDX, Syft",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "repository_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.Vulnerability": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "cvss": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "osv_id": {
                    "type": "string"
                },
                "severity": {
                    "description": "CRITICAL, HIGH, MEDIUM, LOW",
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Scapegoat API",
	Description:      "This is the Scapegoat SBOM and Vulnerability Management API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
